<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */


/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 * @var \Opengento\Hoodoor\ViewModel\Request\Login $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getData('login_view_model');
?>

<form method="post" action="<?= $escaper->escapeHtmlAttr($viewModel->getPostActionUrl()) ?>" id="login-form" data-mage-init='{"validation": {}}' autocomplete="off">
    <fieldset class="admin__fieldset">
        <legend class="admin__legend">
            <span><?= $escaper->escapeHtml(__('Welcome, please sign in')) ?></span>
        </legend><br/>
        <input name="form_key" type="hidden" value="<?= $escaper->escapeHtmlAttr($block->getFormKey()) ?>" />
        <div class="admin__field _required field-username">
            <label for="username" class="admin__field-label">
                <span><?= $escaper->escapeHtml(__('Email')) ?></span>
            </label>
            <div class="admin__field-control">
                <input id="username"
                       class="admin__control-text"
                       type="text"
                       name="login[username]"
                       autofocus
                       value=""
                       data-validate="{required:true}"
                       autocomplete="off"
                    />
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
        <div class="form-actions">
            <div class="actions">
                <button type="submit" class="action-login action-primary">
                    <span class="sparkle">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
                        </svg>
                    </span>
                    <span><?= $escaper->escapeHtml(__('Send Magic Link')) ?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>
